autoDetectedPackages:
- aqs
- collections
- currents
- io
- proxy
- schedule
- spi
- spring.context
- spring.ioc
- thread
enableAutoDetect: true
funcDisplayConfig:
  skipConstructors: false
  skipFieldAccess: true
  skipFieldChange: true
  skipGetters: true
  skipPrivateMethods: false
  skipSetters: true
ignoreSameClassCall: null
ignoreSamePackageCall: null
includedPackagePrefixes: null
includedParentClasses: null
name: xcodemap-filter
recordMode: smart
startOnDebug: false
